"""Home Report pipeline — single PDF → full analysis HTML + storage.

End-to-end flow:
  1. parse PDF with `parse_home_report.py` → parsed.json
  2. PropertyRecord.from_parsed(parsed)
  3. (optional) area_data.fetch(postcode)
  4. scoring.compute(record)
  5. load SurveyorOpinion JSON (caller provides path — generated by SKILL.md)
  6. opinion.validate(parsed) → raise on errors
  7. renderer.render_home_report(...)
  8. storage.upsert_property(record) + storage.attach_html_report(...)

The opinion JSON file is the LLM's responsibility (SKILL.md generates it,
this pipeline only consumes). For tests/CI, a fixture opinion can be supplied.
"""

from __future__ import annotations

import json
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from property_assistant.analysis.scoring import ScoreBreakdown, compute
from property_assistant.analysis.surveyor_opinion import SurveyorOpinion
from property_assistant.core.property_record import PropertyRecord
from property_assistant.render.renderer import render_home_report
from property_assistant.storage import get_storage


PARSE_SCRIPT = Path(__file__).resolve().parent.parent / "parse_home_report.py"


class OpinionValidationError(Exception):
    """Raised when SurveyorOpinion fails validate() — caller should regenerate."""

    def __init__(self, errors: list[str]):
        self.errors = errors
        super().__init__("SurveyorOpinion validation failed:\n" + "\n".join(f"- {e}" for e in errors))


@dataclass
class RunResult:
    record: PropertyRecord
    breakdown: ScoreBreakdown
    html_path: Path
    property_id: str
    parsed_path: Path
    opinion_path: Path | None


def parse_pdf(pdf_path: Path) -> dict[str, Any]:
    """Run parse_home_report.py and return its JSON output."""
    if not PARSE_SCRIPT.exists():
        raise FileNotFoundError(f"parser script not found: {PARSE_SCRIPT}")
    proc = subprocess.run(
        [sys.executable, str(PARSE_SCRIPT), str(pdf_path)],
        capture_output=True, text=True, timeout=120,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"parse_home_report.py failed (exit {proc.returncode}):\n{proc.stderr[:2000]}"
        )
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"parser output not valid JSON: {exc}\nFirst 500 chars: {proc.stdout[:500]}")


def run(
    pdf_path: Path | str,
    *,
    opinion_path: Path | str,
    out_html: Path | str | None = None,
    parsed: dict[str, Any] | None = None,
    area: dict[str, Any] | None = None,
    skip_storage: bool = False,
) -> RunResult:
    """Execute the full pipeline.

    Args:
        pdf_path: source PDF
        opinion_path: pre-generated SurveyorOpinion JSON
                     (in production: written by SKILL.md before calling this)
        out_html: HTML output path (default: alongside PDF as <name>_analysis.html)
        parsed: pre-parsed JSON, skips re-parsing if provided (mainly for tests)
        area: pre-fetched area data dict (optional)
        skip_storage: if True, do not write to backend storage (for previews)
    """
    pdf_path = Path(pdf_path).expanduser().resolve()
    opinion_path = Path(opinion_path).expanduser().resolve()

    # 1. Parse PDF (or use injected parsed)
    if parsed is None:
        parsed = parse_pdf(pdf_path)
    parsed_dump_path = pdf_path.with_suffix("").with_name(pdf_path.stem + "_parsed.json")
    parsed_dump_path.write_text(
        json.dumps(parsed, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    # 2. PropertyRecord
    record = PropertyRecord.from_parsed(parsed)
    record.pdf_path = str(pdf_path)

    # 3. Score
    breakdown = compute(record)

    # 4. Load + validate opinion
    opinion = SurveyorOpinion.from_json_file(str(opinion_path))
    errs = opinion.validate(parsed)
    if errs:
        raise OpinionValidationError(errs)

    # 5. Render HTML
    out_html = Path(out_html).expanduser().resolve() if out_html else \
               pdf_path.with_name(record.address_slug() + "_analysis.html")
    storage_backend_name = None
    if not skip_storage:
        storage = get_storage()
        storage_backend_name = storage.name
    render_home_report(
        record=record,
        breakdown=breakdown,
        opinion=opinion,
        parsed=parsed,
        area=area,
        out_path=out_html,
        storage_backend=storage_backend_name,
    )

    # 6. Storage
    pid = ""
    if not skip_storage:
        pid = storage.upsert_property(record)
        try:
            storage.attach_html_report(pid, str(out_html), "home_report")
        except Exception as exc:  # noqa: BLE001
            print(f"warning: attach_html_report failed: {exc}", file=sys.stderr)

    return RunResult(
        record=record,
        breakdown=breakdown,
        html_path=out_html,
        property_id=pid,
        parsed_path=parsed_dump_path,
        opinion_path=opinion_path,
    )


def _cli() -> int:
    import argparse
    ap = argparse.ArgumentParser(
        prog="python -m property_assistant.pipelines.home_report",
        description="Run the full Home Report pipeline.",
    )
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("run", help="Run pipeline on a PDF")
    r.add_argument("pdf", help="Home Report PDF path")
    r.add_argument("--opinion", required=True, help="SurveyorOpinion JSON path")
    r.add_argument("--parsed", help="Pre-parsed JSON path (skips re-parsing)")
    r.add_argument("--out", help="HTML output path (default: <pdf>_analysis.html)")
    r.add_argument("--skip-storage", action="store_true",
                   help="Don't write to backend storage (preview-only)")
    args = ap.parse_args()

    if args.cmd != "run":
        return 2

    parsed_dict = None
    if args.parsed:
        with open(args.parsed, encoding="utf-8") as f:
            parsed_dict = json.load(f)

    try:
        result = run(
            args.pdf,
            opinion_path=args.opinion,
            out_html=args.out,
            parsed=parsed_dict,
            skip_storage=args.skip_storage,
        )
    except OpinionValidationError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    except Exception as exc:  # noqa: BLE001
        print(f"pipeline failed: {exc}", file=sys.stderr)
        return 1

    print(f"✓ HTML: {result.html_path}")
    print(f"  Score: {result.breakdown.total}/100 · {result.breakdown.recommendation}")
    print(f"  Address: {result.record.address}")
    if result.property_id:
        print(f"  Storage ID: {result.property_id}")
    return 0


if __name__ == "__main__":
    sys.exit(_cli())
