"""Home Report pipeline — single PDF → full analysis HTML + storage.

End-to-end flow:
  1. parse PDF with `parse_home_report.py` → parsed.json
  2. PropertyRecord.from_parsed(parsed)
  3. (optional) area_data.fetch(postcode)
  4. scoring.compute(record)
  5. load SurveyorOpinion JSON (caller provides path — generated by SKILL.md)
  6. opinion.validate(parsed) → raise on errors
  7. renderer.render_home_report(...)
  8. storage.upsert_property(record) + storage.attach_html_report(...)

The opinion JSON file is the LLM's responsibility (SKILL.md generates it,
this pipeline only consumes). For tests/CI, a fixture opinion can be supplied.
"""

from __future__ import annotations

import json
import subprocess
import sys
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Any

from property_assistant.analysis.scoring import ScoreBreakdown, compute
from property_assistant.analysis.surveyor_opinion import SurveyorOpinion
from property_assistant.core.property_record import PropertyRecord
from property_assistant.parsers.rightmove import fetch_listing_meta
from property_assistant.render.renderer import render_home_report
from property_assistant.storage import get_storage


PARSE_SCRIPT = Path(__file__).resolve().parent.parent / "parse_home_report.py"
AREA_SCRIPT = Path(__file__).resolve().parent.parent / "fetch_area_data.py"


class OpinionValidationError(Exception):
    """Raised when SurveyorOpinion fails validate() — caller should regenerate."""

    def __init__(self, errors: list[str]):
        self.errors = errors
        super().__init__("SurveyorOpinion validation failed:\n" + "\n".join(f"- {e}" for e in errors))


@dataclass
class RunResult:
    record: PropertyRecord
    breakdown: ScoreBreakdown
    html_path: Path
    property_id: str
    parsed_path: Path
    opinion_path: Path | None


def parse_pdf(pdf_path: Path) -> dict[str, Any]:
    """Run parse_home_report.py and return its JSON output."""
    if not PARSE_SCRIPT.exists():
        raise FileNotFoundError(f"parser script not found: {PARSE_SCRIPT}")
    proc = subprocess.run(
        [sys.executable, str(PARSE_SCRIPT), str(pdf_path)],
        capture_output=True, text=True, timeout=120,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"parse_home_report.py failed (exit {proc.returncode}):\n{proc.stderr[:2000]}"
        )
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"parser output not valid JSON: {exc}\nFirst 500 chars: {proc.stdout[:500]}")


def fetch_area(postcode: str) -> dict[str, Any] | None:
    """Run fetch_area_data.py for postcode → dict (or None on failure).

    Never raises — area data is enrichment, not blocking. Skips SIMD/flood
    if they're slow; keeps schools (the only one we currently feed back
    into PropertyRecord).
    """
    if not AREA_SCRIPT.exists() or not postcode:
        return None
    try:
        proc = subprocess.run(
            [sys.executable, str(AREA_SCRIPT), "--postcode", postcode],
            capture_output=True, text=True, timeout=60,
        )
        if proc.returncode != 0:
            return None
        return json.loads(proc.stdout)
    except Exception:
        return None


def parse_viewing(s: str) -> tuple[date, str]:
    """Parse '2026-05-29' or '2026-05-29 18:30' → (date, iso_with_tz_or_date).

    Wall-clock time interpreted as Europe/London — Notion gets the correct
    BST/GMT offset for any date (user-memory rule: never UTC).
    """
    s = s.strip()
    if " " in s:
        d_part, t_part = s.split(" ", 1)
    elif "T" in s:
        d_part, t_part = s.split("T", 1)
    else:
        d_part, t_part = s, None
    d = date.fromisoformat(d_part)
    if t_part is None:
        return d, d.isoformat()
    try:
        from zoneinfo import ZoneInfo
        tz = ZoneInfo("Europe/London")
    except Exception:  # noqa: BLE001 — fallback for ancient Pythons
        tz = None
    hhmm = (t_part if len(t_part) >= 5 else f"{t_part}:00")[:5]
    hour, minute = (int(x) for x in hhmm.split(":"))
    dt = datetime(d.year, d.month, d.day, hour, minute, 0, tzinfo=tz)
    return d, dt.isoformat()


def run(
    pdf_path: Path | str,
    *,
    opinion_path: Path | str,
    out_html: Path | str | None = None,
    parsed: dict[str, Any] | None = None,
    area: dict[str, Any] | None = None,
    listing_url: str | None = None,
    viewing: str | None = None,
    skip_storage: bool = False,
    skip_area: bool = False,
) -> RunResult:
    """Execute the full pipeline.

    Args:
        pdf_path: source PDF
        opinion_path: pre-generated SurveyorOpinion JSON
                     (in production: written by SKILL.md before calling this)
        out_html: HTML output path (default: alongside PDF as <name>_analysis.html)
        parsed: pre-parsed JSON, skips re-parsing if provided (mainly for tests)
        area: pre-fetched area data dict (optional). If None and skip_area
              is False, this pipeline runs fetch_area_data.py for postcode.
        listing_url: Rightmove URL — scraped for cover image + asking price,
                     written into PropertyRecord.{listing_url, asking_price};
                     image_url passed to storage as page cover (Notion).
        viewing: "YYYY-MM-DD" or "YYYY-MM-DD HH:MM" wall-clock (Europe/London)
                 → record.viewing_date + full ISO datetime for Notion patch.
        skip_storage: if True, do not write to backend storage (for previews)
        skip_area: if True, do not call fetch_area_data.py
    """
    pdf_path = Path(pdf_path).expanduser().resolve()
    opinion_path = Path(opinion_path).expanduser().resolve()

    # 1. Parse PDF (or use injected parsed)
    if parsed is None:
        parsed = parse_pdf(pdf_path)
    parsed_dump_path = pdf_path.with_suffix("").with_name(pdf_path.stem + "_parsed.json")
    parsed_dump_path.write_text(
        json.dumps(parsed, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    # 2. PropertyRecord
    record = PropertyRecord.from_parsed(parsed)
    record.pdf_path = str(pdf_path)

    # 2.5 Area data (lat/lon, SIMD, flood, schools, commute) — non-blocking enrichment
    if area is None and not skip_area and record.postcode:
        area = fetch_area(record.postcode)
    if area:
        flat = area.get("schools_flat") or []
        if flat and not record.school_zone:
            record.school_zone = flat
        # Persist SIMD / flood / commute back to PropertyRecord so they reach
        # storage (Notion columns + LocalJSON) and downstream scoring/preference
        # loop. fetch_area_data outputs flat keys — map them onto PropertyRecord.
        if record.simd_decile is None and area.get("simd_overall_decile") is not None:
            record.simd_decile = int(area["simd_overall_decile"])
        if record.flood_risk is None and area.get("flood_risk"):
            record.flood_risk = str(area["flood_risk"])
        if record.commute_user_min is None and area.get("commute_user_min") is not None:
            record.commute_user_min = int(area["commute_user_min"])
        if record.commute_partner_min is None and area.get("commute_partner_min") is not None:
            record.commute_partner_min = int(area["commute_partner_min"])

    # 2.6 Rightmove listing meta — fills listing_url + asking_price + cover
    cover_url: str | None = None
    if listing_url:
        meta = fetch_listing_meta(listing_url)
        record.listing_url = listing_url
        if meta.get("asking_price") and not record.asking_price:
            record.asking_price = float(meta["asking_price"])
        cover_url = meta.get("image_url")
        if meta.get("error"):
            print(f"warning: rightmove scrape: {meta['error']}", file=sys.stderr)

    # 2.7 Viewing date — record.viewing_date is `date`; Notion needs datetime
    viewing_iso: str | None = None
    if viewing:
        d_val, viewing_iso = parse_viewing(viewing)
        record.viewing_date = d_val

    # 3. Score
    breakdown = compute(record)

    # 4. Load + validate opinion
    opinion = SurveyorOpinion.from_json_file(str(opinion_path))
    errs = opinion.validate(parsed)
    if errs:
        raise OpinionValidationError(errs)

    # 5. Render HTML
    out_html = Path(out_html).expanduser().resolve() if out_html else \
               pdf_path.with_name(record.address_slug() + "_analysis.html")
    storage_backend_name = None
    if not skip_storage:
        storage = get_storage()
        storage_backend_name = storage.name
    render_home_report(
        record=record,
        breakdown=breakdown,
        opinion=opinion,
        parsed=parsed,
        area=area,
        out_path=out_html,
        storage_backend=storage_backend_name,
    )

    # 6. Storage
    pid = ""
    if not skip_storage:
        pid = storage.upsert_property(record)
        try:
            storage.attach_html_report(pid, str(out_html), "home_report")
        except Exception as exc:  # noqa: BLE001
            print(f"warning: attach_html_report failed: {exc}", file=sys.stderr)
        try:
            storage.set_tldr(pid, opinion.derive_tldr())
        except Exception as exc:  # noqa: BLE001
            print(f"warning: set_tldr failed: {exc}", file=sys.stderr)
        # Notion-only post-upsert patches (cover image + full viewing datetime)
        if storage_backend_name == "notion" and pid and (cover_url or viewing_iso):
            try:
                _notion_post_patch(storage, pid, cover_url=cover_url,
                                   viewing_iso=viewing_iso)
            except Exception as exc:  # noqa: BLE001
                print(f"warning: notion post-patch failed: {exc}", file=sys.stderr)

    return RunResult(
        record=record,
        breakdown=breakdown,
        html_path=out_html,
        property_id=pid,
        parsed_path=parsed_dump_path,
        opinion_path=opinion_path,
    )


def _notion_post_patch(storage, page_id: str, *, cover_url: str | None,
                       viewing_iso: str | None) -> None:
    """Apply Notion-specific fields the default upsert can't express.

    - cover image: Notion API supports `cover.external.url` on the page level
    - viewing datetime: the default `date` converter strips the time part,
      so we PATCH the raw ISO with offset directly.
    """
    payload: dict = {}
    if cover_url:
        payload["cover"] = {"type": "external", "external": {"url": cover_url}}
    if viewing_iso and "T" in viewing_iso:
        payload.setdefault("properties", {})["Viewing时间"] = {
            "date": {"start": viewing_iso}
        }
    if not payload:
        return
    # Reuse the storage's HTTP layer for auth + headers.
    storage._request("PATCH", f"/pages/{page_id}", payload)


def _cli() -> int:
    import argparse
    ap = argparse.ArgumentParser(
        prog="python -m property_assistant.pipelines.home_report",
        description="Run the full Home Report pipeline.",
    )
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("run", help="Run pipeline on a PDF")
    r.add_argument("pdf", help="Home Report PDF path")
    r.add_argument("--opinion", required=True, help="SurveyorOpinion JSON path")
    r.add_argument("--parsed", help="Pre-parsed JSON path (skips re-parsing)")
    r.add_argument("--out", help="HTML output path (default: <pdf>_analysis.html)")
    r.add_argument("--listing", help="Rightmove URL — scrapes cover image + asking price")
    r.add_argument("--viewing", help="'YYYY-MM-DD' or 'YYYY-MM-DD HH:MM' wall-clock (Europe/London)")
    r.add_argument("--skip-storage", action="store_true",
                   help="Don't write to backend storage (preview-only)")
    r.add_argument("--skip-area", action="store_true",
                   help="Skip fetch_area_data.py (no SIMD/flood/school enrichment)")
    args = ap.parse_args()

    if args.cmd != "run":
        return 2

    parsed_dict = None
    if args.parsed:
        with open(args.parsed, encoding="utf-8") as f:
            parsed_dict = json.load(f)

    try:
        result = run(
            args.pdf,
            opinion_path=args.opinion,
            out_html=args.out,
            parsed=parsed_dict,
            listing_url=args.listing,
            viewing=args.viewing,
            skip_storage=args.skip_storage,
            skip_area=args.skip_area,
        )
    except OpinionValidationError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    except Exception as exc:  # noqa: BLE001
        print(f"pipeline failed: {exc}", file=sys.stderr)
        return 1

    print(f"✓ HTML: {result.html_path}")
    print(f"  Score: {result.breakdown.total}/100 · {result.breakdown.recommendation}")
    print(f"  Address: {result.record.address}")
    if result.property_id:
        print(f"  Storage ID: {result.property_id}")
    return 0


if __name__ == "__main__":
    sys.exit(_cli())
